<a href="https://colab.research.google.com/github/himanshisangani64-beep/numpy_all_code/blob/main/csv_excel_file_read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Reading and Writing CSV, JSON, and Excel Files

Task 1: Read a CSV file into a DataFrame

In [1]:
import pandas as pd

In [14]:
from numpy import nan
sample_data = {"id":[1,2,3,4,5,1],
               "name":["ram","siya",nan,"jiya","Tina","ram"],
               "city":["Rajkot","Amreli","Surat","jaypur","Amreli","Rajkot"],
               "Salary":["20000","30000",nan,"50000","30000","20000"],
               "Age":[19,21,30,25,20,19],
               "Date":["1-1-2025","13-1-2025","23-1-2025","31-1-2025"," 1-2-2025","1-1-2025"],
               "Gender":["male",nan,"male","female","female","male"]
               }
df = pd.DataFrame(sample_data)
df.to_csv(r"/content/sample_data09.csv", index=False)

Task 2: Save the DataFrame into a new Excel file named 'output_data.xlsx'

In [11]:
df.to_csv(r"/content/output_data09.xlsx", index=False)

Task 3: Load a JSON file named 'sample_data.json' into a DataFrame

In [12]:
df.to_csv(r"/content/sample_data09.json", index=False)

Task 4: Convert a DataFrame into a JSON file named 'export_data.json'

In [13]:
df.to_csv(r"/content/export_data.json", index=False)

2. Handling Missing Values, Duplicates, and Data Types

Task 5: Load a DataFrame with missing values and fill them with appropriate values

In [15]:
df1 = pd.read_csv("/content/sample_data09.csv")
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
1   2  siya  Amreli  30000.0   21  13-1-2025     NaN
2   3   NaN   Surat      NaN   30  23-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female
5   1   ram  Rajkot  20000.0   19   1-1-2025    male

In [16]:
df1['name'].ffill(inplace=True)

/tmp/ipykernel_2490/2223248708.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['name'].ffill(inplace=True)

In [17]:
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
1   2  siya  Amreli  30000.0   21  13-1-2025     NaN
2   3  siya   Surat      NaN   30  23-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female
5   1   ram  Rajkot  20000.0   19   1-1-2025    male

In [18]:
df1['city'].bfill(inplace=True)

/tmp/ipykernel_2490/2269900027.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['city'].bfill(inplace=True)

In [19]:
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
1   2  siya  Amreli  30000.0   21  13-1-2025     NaN
2   3  siya   Surat      NaN   30  23-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female
5   1   ram  Rajkot  20000.0   19   1-1-2025    male

In [25]:
df1['Salary'].bfill(inplace=True)

/tmp/ipykernel_2490/1232580666.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Salary'].bfill(inplace=True)

In [35]:
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
1   2  siya  Amreli  30000.0   21  13-1-2025    male
2   3  siya   Surat  50000.0   30  23-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female
5   1   ram  Rajkot  20000.0   19   1-1-2025    male

Task 6: Drop rows where any value is missing

In [57]:
df1 = pd.read_csv("/content/sample_data09.csv")
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
1   2  siya  Amreli  30000.0   21  13-1-2025     NaN
2   3   NaN   Surat      NaN   30  23-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female
5   1   ram  Rajkot  20000.0   19   1-1-2025    male

In [58]:
df1.dropna(inplace=True)

Task 7: Identify and remove duplicate rows

In [59]:
df1[df1.duplicated()]

   id name    city   Salary  Age      Date Gender
5   1  ram  Rajkot  20000.0   19  1-1-2025   male

In [60]:
df1.drop_duplicates(inplace=True)

In [61]:
df1

   id  name    city   Salary  Age       Date  Gender
0   1   ram  Rajkot  20000.0   19   1-1-2025    male
3   4  jiya  jaypur  50000.0   25  31-1-2025  female
4   5  Tina  Amreli  30000.0   20   1-2-2025  female

In [62]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 4
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   name    3 non-null      object
 2   city    3 non-null      object
 3   Salary  3 non-null      float64
 4   Age     3 non-null      int64
 5   Date    3 non-null      object
 6   Gender  3 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 192.0+ bytes

Task 8: Convert a column from string to numeric (handle errors gracefully)

In [67]:
df1['Salary'] = df1['Salary'].astype(dtype="int")

Task 9: Check and change data types of columns in a DataFrame

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 4
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   name    3 non-null      object
 2   city    3 non-null      object
 3   Salary  3 non-null      int64
 4   Age     3 non-null      int64
 5   Date    3 non-null      object
 6   Gender  3 non-null      object
dtypes: int64(3), object(4)
memory usage: 192.0+ bytes

3. Handling Dates and Times using Pandas

Task 10: Load a DataFrame containing a 'date' column with string format, and convert it to datetime

In [69]:
df1['Date']

0     1-1-2025
3    31-1-2025
4     1-2-2025
Name: Date, dtype: object

In [71]:
df1["New_Date"] = pd.to_datetime(df['Date'],format="%d-%m-%Y")

In [73]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 4
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3 non-null      int64
 1   name      3 non-null      object
 2   city      3 non-null      object
 3   Salary    3 non-null      int64
 4   Age       3 non-null      int64
 5   Date      3 non-null      object
 6   Gender    3 non-null      object
 7   New_Date  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 216.0+ bytes

Task 11: Extract year, month, and day from the datetime column

In [79]:
df1["year"] = df1['New_Date'].dt.year

In [80]:
df1["Month"] = df1['New_Date'].dt.month

In [81]:
df1["Day"] = df1['New_Date'].dt.day

In [82]:
df1

,id,name,city,Salary,Age,Date,Gender,New_Date,year,Month,Day
0,1,ram,Rajkot,20000,19,1-1-2025,male,2025-01-01,2025,1,1
3,4,jiya,jaypur,50000,25,31-1-2025,female,2025-01-31,2025,1,31
4,5,Tina,Amreli,30000,20,1-2-2025,female,2025-02-01,2025,2,1

Task 12: Filter the DataFrame for rows within a specific date range

In [87]:
df1[df1['New_Date']=="2025-01-01"]

   id name    city  Salary  Age      Date Gender   New_Date  year  Month  Day
0   1  ram  Rajkot   20000   19  1-1-2025   male 2025-01-01  2025      1    1

Task 13: Create a new column with the difference in days between two datetime columns

In [100]:
start_date = pd.to_datetime(df1['New_Date'].iloc[0])
end_date = pd.to_datetime(df1['New_Date'].iloc[1])
day = (end_date - start_date).days
print("Total Difference Day",day)

Total Difference Day 30