<a href="https://colab.research.google.com/github/himanshisangani64-beep/numpy_all_code/blob/main/Pandas_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Introduction to Pandas

Task 1.1: Importing Pandas

In [2]:
import pandas as pd

Task 1.2: Understanding Pandas Data Structures

In [3]:
#  two primary data structures in Pandas means
# pandas is python power full library
# pandas in two primary data structer use
# pandas in Series and Dataframe use
# Series is singel column data and multipel rows
# dataframe is two or more column and row
# pandas in  row and column structer in data are show mostly

2. Series

Task 2.1: Creating a Series from a List

In [5]:
fruits = ['apple', 'banana', 'cherry', 'date']
s = pd.Series(data=fruits,name="fruits")
s

0     apple
1    banana
2    cherry
3      date
Name: fruits, dtype: object

Task 2.2: Creating a Series with Custom Indices

In [6]:
color  = {"color1":"red","color2":"green","color3":"blue"}
c = pd.Series(data=color,index=["color1","color2","color3"],name="colors")
c

color1      red
color2    green
color3     blue
Name: colors, dtype: object

Task 2.3: Accessing Elements in a Series

In [9]:
# Using the fruits Series, access and print the element at index 1
s[1]

'banana'

In [10]:
# Using the colors Series, access and print the element with the index 'color2'.
c["color2"]

'green'

3. DataFrame

Task 3.1: Creating a DataFrame from a Dictionary of Lists

In [60]:
student_data = {
'name': ['Alice', 'Bob', 'Charlie'],
'age': [20, 21, 19],
'major': ['CS', 'Engineering', 'Math']
}
dfs = pd.DataFrame(student_data)
dfs

      name  age        major
0    Alice   20           CS
1      Bob   21  Engineering
2  Charlie   19         Math

Task 3.2: Creating a DataFrame from a List of Dictionaries

In [91]:
employee_data = {"name":["David","Eve","Frank"],
                 "salary":[50000,60000,55000],
                 "department":["Sales","Marketing","Sales"]}
dfe = pd.DataFrame(employee_data)
dfe

    name  salary department
0  David   50000      Sales
1    Eve   60000  Marketing
2  Frank   55000      Sales

Task 3.3: Creating a DataFrame from a NumPy Array

In [13]:
import numpy as np

In [19]:
data_array = np.array([[5,6],[7,5],[8,4]])
data_array.shape

(3, 2)

In [29]:
data_array

array([[5, 6],
       [7, 5],
       [8, 4]])

In [40]:
random_df = {"Cloumn1":data_array[0:3,0],
             "Cloumn2":data_array[0:3,1]
             }
df = pd.DataFrame(random_df)
df

   Cloumn1  Cloumn2
0        5        6
1        7        5
2        8        4

4. Exploring Data (Series and DataFrame)

Task 4.1: Exploring a Series

In [41]:
# The number of elements in the Series
s.shape

(4,)

In [58]:
#The unique values in the Series
s.unique()

array(['apple', 'banana', 'cherry', 'date'], dtype=object)

In [59]:
#The count of each unique value in the Series
s.value_counts()

fruits
apple     1
banana    1
cherry    1
date      1
Name: count, dtype: int64

Task 4.2: Exploring a DataFrame

In [61]:
# student_data
# The first 2 rows of the DataFrame.
dfs.head(2)

    name  age        major
0  Alice   20           CS
1    Bob   21  Engineering

In [62]:
# The last row of the DataFrame.
dfs.tail(2)

      name  age        major
1      Bob   21  Engineering
2  Charlie   19         Math

In [66]:
# The index of the DataFrame
dfs.index

RangeIndex(start=0, stop=3, step=1)

In [67]:
# The column names of the DataFrame
dfs.columns

Index(['name', 'age', 'major'], dtype='object')

In [68]:
#  A concise summary of the DataFrame (including data types and non-null values).
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   major   3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

Task 4.3: Selecting Columns and Rows

In [70]:
# employee_data
# Select and print only the 'name' column
dfe['name']

0    David
1      Eve
2    Frank
Name: name, dtype: object

In [74]:
#  Select and print the row at index 1.
dfe.iloc[1]

name                Eve
salary            60000
department    Marketing
Name: 1, dtype: object

In [75]:
# Select and print the 'name' and 'salary' columns.
dfe[['name','salary']]

    name  salary
0  David   50000
1    Eve   60000
2  Frank   55000

In [76]:
# Select and print the first two rows and the 'name' and 'department' columns
dfe[['name','department']].iloc[0:2]

    name department
0  David      Sales
1    Eve  Marketing

5. Operations on DataFrames

Task 5.1: Adding a New Column

In [77]:
dfs["City"]= ['New York', 'London', 'Paris']
dfs

      name  age        major      City
0    Alice   20           CS  New York
1      Bob   21  Engineering    London
2  Charlie   19         Math     Paris

Task 5.2: Removing a Column

In [79]:
dfs.drop(['City'],axis=1)

      name  age        major
0    Alice   20           CS
1      Bob   21  Engineering
2  Charlie   19         Math

Task 5.3: Filtering Rows Based on a Condition

In [80]:
# Using the employee_data DataFrame, filter and print the rows where the 'department' is 'Sales'.
dfe[dfe['department']=='Sales']

    name  salary department
0  David   50000      Sales
2  Frank   55000      Sales

Task 5.4: Sorting a DataFrame

In [106]:
# Sort the employee_data DataFrame by the 'salary' column in descending order

d = dfe['salary'].sort_values(ascending=False)
d

1    60000
2    55000
0    50000
Name: salary, dtype: int64

Task 5.5: Basic Aggregation

In [111]:
# Using the employee_data DataFrame, calculate and print the average salary of all employees.
Average_Salary = dfe['salary'].sum() / 3
Average_Salary

np.float64(55000.0)